import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { createI18n } from 'vue-i18n'
import './assets/styles.css'

const messages = {
  en: {
    title: 'Luca Newsletter',
    description: 'Welcome to the Luca Newsletter, your daily dose of knowledge, inspiration, and fun! Our carefully curated content is designed to kickstart your day with a perfect blend of information, language learning, and personal growth.',
    subscribeTitle: 'Subscribe',
    subscribePlaceholder: 'Enter your email',
    subscribeButton: 'Join the Future',
    unsubscribeTitle: 'Unsubscribe',
    unsubscribePlaceholder: 'Enter your email to unsubscribe',
    unsubscribeButton: 'Leave the Network',
    weather: 'Weather',
    weatherDesc: 'Stay informed about the day\'s forecast.',
    exchangeRates: 'Exchange Rates',
    exchangeRatesDesc: 'Keep track of the latest currency exchange rates.',
    quoteOfTheDay: 'Quote of the Day',
    quoteOfTheDayDesc: 'Get inspired by thought-provoking quotes.',
    funFact: 'Fun Fact',
    funFactDesc: 'Learn something new and interesting every day.',
    englishWithLuca: 'English with Luca',
    englishWithLucaDesc: 'Improve your English with our Word of the Day and Tip of the Day.',
    onThisDay: 'On This Day',
    onThisDayDesc: 'Discover a significant historical event that occurred on this date.',
    breathingBox: 'Breathing Box',
    breathingBoxDesc: 'Practice mindfulness with our daily breathing exercise gif.',
    dailyChallenge: 'Daily Challenge',
    dailyChallengeDesc: 'Push yourself with a new personal growth challenge each day.',
    subscribeNow: 'Subscribe Now',
    unsubscribe: 'Unsubscribe',
    backToHome: 'Back to Home',
    editPreferencesTitle: 'Edit Newsletter Preferences',
    newsletterSections: 'Newsletter Sections',
    deliveryDays: 'Delivery Days',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    sunday: 'Sunday',
    interests: 'Interests',
    interest1Placeholder: 'Interest 1',
    interest2Placeholder: 'Interest 2',
    interest3Placeholder: 'Interest 3',
    language: 'Language',
    languageEnglish: 'English',
    languagePortuguese: 'Portuguese',
    languageBoth: 'Both',
    savePreferences: 'Save Preferences',
    editPreferences: 'Edit Preferences',
    submitErrorTitle: 'Submit an Error',
    submitRequestTitle: 'Submit a Request',
    subjectPlaceholder: 'Subject',
    errorDescriptionPlaceholder: 'Describe the error',
    requestDescriptionPlaceholder: 'Describe your request',
    attachmentLabel: 'Attach Screenshot (optional)',
    submitError: 'Submit Error',
    submitRequest: 'Submit Request',
    submitErrorButton: 'Submit an Error',
    submitRequestButton: 'Submit a Request',
    subscribeSuccessTitle: 'Subscription Successful!',
    subscribeSuccessMessage: 'Thank you for joining the Luca Newsletter!',
    unsubscribeSuccessTitle: 'Unsubscribe Successful',
    unsubscribeSuccessMessage: 'We\'re sorry to see you go!',
    submitting: 'Submitting... Please wait',
    successTitle: 'Success!',
    successMessage: 'Your form has been submitted successfully.',
    cityPlaceholder: "Enter your city",
    countryPlaceholder: "Enter your country",
    languageEnglishPortuguese: "English & Portuguese",
    location: "Location",
  },
  pt: {
    title: 'Boletim Luca',
    description: 'Bem-vindo ao Boletim Luca, sua dose diária de conhecimento, inspiração e diversão! Nosso conteúdo cuidadosamente selecionado foi projetado para iniciar seu dia com uma mistura perfeita de informação, aprendizado de idiomas e crescimento pessoal.',
    subscribeTitle: 'Inscrever-se',
    subscribePlaceholder: 'Digite seu e-mail',
    subscribeButton: 'Junte-se ao Futuro',
    unsubscribeTitle: 'Cancelar inscrição',
    unsubscribePlaceholder: 'Digite seu e-mail para cancelar a inscrição',
    unsubscribeButton: 'Sair da Rede',
    weather: 'Tempo',
    weatherDesc: 'Fique informado sobre a previsão do dia.',
    exchangeRates: 'Taxas de Câmbio',
    exchangeRatesDesc: 'Acompanhe as últimas taxas de câmbio de moedas.',
    quoteOfTheDay: 'Citação do Dia',
    quoteOfTheDayDesc: 'Inspire-se com citações estimulantes.',
    funFact: 'Curiosidade',
    funFactDesc: 'Aprenda algo novo e interessante todos os dias.',
    englishWithLuca: 'Inglês com Luca',
    englishWithLucaDesc: 'Melhore seu inglês com nossa Palavra do Dia e Dica do Dia.',
    onThisDay: 'Neste Dia',
    onThisDayDesc: 'Descubra um evento histórico significativo que ocorreu nesta data.',
    breathingBox: 'Caixa de Respiração',
    breathingBoxDesc: 'Pratique mindfulness com nosso gif diário de exercício de respiração.',
    dailyChallenge: 'Desafio Diário',
    dailyChallengeDesc: 'Desafie-se com um novo desafio de crescimento pessoal a cada dia.',
    subscribeNow: 'Inscreva-se Agora',
    unsubscribe: 'Cancelar Inscrição',
    backToHome: 'Voltar para a Página Inicial',
    editPreferencesTitle: 'Editar Preferências da Newsletter',
    newsletterSections: 'Seções da Newsletter',
    deliveryDays: 'Dias de Entrega',
    monday: 'Segunda-feira',
    tuesday: 'Terça-feira',
    wednesday: 'Quarta-feira',
    thursday: 'Quinta-feira',
    friday: 'Sexta-feira',
    saturday: 'Sábado',
    sunday: 'Domingo',
    interests: 'Interesses',
    interest1Placeholder: 'Interesse 1',
    interest2Placeholder: 'Interesse 2',
    interest3Placeholder: 'Interesse 3',
    language: 'Idioma',
    languageEnglish: 'Inglês',
    languagePortuguese: 'Português',
    languageBoth: 'Ambos',
    savePreferences: 'Salvar Preferências',
    editPreferences: 'Editar Preferências',
    submitErrorTitle: 'Reportar um Erro',
    submitRequestTitle: 'Enviar uma Solicitação',
    subjectPlaceholder: 'Assunto',
    errorDescriptionPlaceholder: 'Descreva o erro',
    requestDescriptionPlaceholder: 'Descreva sua solicitação',
    attachmentLabel: 'Anexar Captura de Tela (opcional)',
    submitError: 'Enviar Erro',
    submitRequest: 'Enviar Solicitação',
    submitErrorButton: 'Reportar um Erro',
    submitRequestButton: 'Enviar uma Solicitação',
    subscribeSuccessTitle: 'Inscrição bem-sucedida!',
    subscribeSuccessMessage: 'Obrigado por se juntar ao Boletim Luca!',
    unsubscribeSuccessTitle: 'Cancelamento de inscrição bem-sucedido',
    unsubscribeSuccessMessage: 'Lamentamos vê-lo partir!',
    submitting: 'Enviando... Aguarde',
    successTitle: 'Sucesso!',
    successMessage: 'Seu formulário foi enviado com sucesso.',
    cityPlaceholder: "Informe sua cidade",
    countryPlaceholder: "Informe seu país",
    languageEnglishPortuguese: "Inglês & Português",
    location: "Localização"
  }
}

const i18n = createI18n({
  locale: 'en', // set locale
  fallbackLocale: 'en', // set fallback locale
  messages, // set locale messages
})

createApp(App).use(router).use(i18n).mount('#app')